---
title: Basil Labs
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Basil Labs
email: connect@basillabs.org
address: 745 ATLANTIC AVENUE, BOSTON MA
tagline: Basil Labs
description: Basil Labs helps your organization understand your consumers, innovate
  and outpace the competition.
baseurl: ''
url: http://127.0.0.1:4000/
paginate: 1000
paginate_path: "/blog/page:num/"
markdown: kramdown
plugins:
- jekyll-sitemap
- jekyll-feed
- jekyll-include-cache
google_analytics: ''
disqus:
  shortname: ''

exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
whitelist:
- jekyll-sitemap
- jekyll-feed
- jekyll-include-cache

footer_title: About Us
footer_description: Basil Labs helps organizations tap into digital and in store consumer intelligence to craft stronger brands and target their audiences with pinpoint accuracy.
copyright_text: Copyright © 2019 All rights reserved to
company_url: "#"